name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk-softfp:latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '10'
    - name: Install dependencies
      run: |
        git clone -b vita-1.19.1 --single-branch https://github.com/isage/openal-soft.git
        cd openal-soft/build
        cmake -DCMAKE_TOOLCHAIN_FILE=${VITASDK}/share/vita.toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS=-mfloat-abi=softfp .. && make -j$(nproc) install
        cd ../..
        git clone https://github.com/Rinnegatamante/vitaGL.git
        make -C vitaGL SOFTFP_ABI=1 NO_DEBUG=1 SAMPLER_UNIFORMS=1 -j$(nproc) install
    - name: Compile project
      run: |
        mkdir build
        cd build
        cmake ..
        make -j$(nproc)
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Get changelog
      id: changelog
      uses: Rinnegatamante/get-git-log-action@master
    - name: Update release body
      id: update_release
      uses: Rinnegatamante/update_release@master
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        release_name: "Nightly ${{ steps.date.outputs.date }}"
        body: "${{ format('{0}\n{1}\n{2}\n{3}\n{4}\n{5}\n{6}\n{7}\n{8}\n{9}', steps.changelog.outputs.log0, steps.changelog.outputs.log1, steps.changelog.outputs.log2, steps.changelog.outputs.log3, steps.changelog.outputs.log4, steps.changelog.outputs.log5, steps.changelog.outputs.log6, steps.changelog.outputs.log7, steps.changelog.outputs.log8, steps.changelog.outputs.log9) }}"
        tag: Nightly
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/YoYoLoader.vpk
        overwrite: true
        tag: Nightly
